print("Welcome to Code Lab 1")
print("My name is Amaan")
print("I go to Bathspa University")
print("I live in Sharjah")
print("I like playing games")
print("I am 20 years old")
print("My birthday is on April 18th")
print("I am Pakistani")
print("I like to bake")
print("I have many friends")